Allow overriding system user on db create.
rsim/oracle-enhanced pull request #2261
Opened 2022-02-09 18:48 UTC by ioev

#2257

Change to allow the a user to specify a different system user.  I went with only allowing via an environment variable, as adding a new $stdin might quality as a breaking change.

2022-02-10 17:00 UTC, akostadinov commented
Looks consistent with SYSTEM password.

2022-02-24 03:48 UTC, yahonda commented on lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb
> +          if ENV["ORACLE_SYSTEM_USER"]
`system_user = ENV["ORACLE_SYSTEM_USER"] || "SYSTEM"` should be fine.

2022-02-24 23:39 UTC, yahonda commented
Please rebase from the master branch to address RSpec failures.

2022-02-26 13:18 UTC, yahonda requested changes

2022-02-26 13:18 UTC, yahonda commented on lib/active_record/connection_adapters/oracle_enhanced/database_tasks.rb
> +          system_username = ENV["ORACLE_SYSTEM_USER"] || 'SYSTEM'
Use double quote "SYSTEM", not 'SYSTEM' to make RuboCop happy.

2026-03-30 20:22 UTC, closed without merging

2026-04-21 18:45 UTC, davidhooey commented
Could we get this pull request merged? When connecting to Oracle Cloud Infrastructure databases the SYSTEM user is not available and we are to use the ADMIN user instead. The ability to override this user is the only way we can use this gem when connecting to an Oracle Cloud Autonomous Database.

2026-04-21 20:46 UTC, yahonda commented
Thanks for the update. I have opened a new one https://github.com/rsim/oracle-enhanced/pull/2569